[mosip_auth]
timestamp_format = "%Y-%m-%dT%H:%M:%S"
ida_auth_version = '1.0'
ida_auth_request_demo_id = 'mosip.identity.auth'
ida_auth_request_kyc_id = 'mosip.identity.kyc'
ida_auth_request_otp_id = 'mosip.identity.otp'
ida_auth_env = 'Staging'
authorization_header_constant = 'Authorization'
partner_apikey = "490669"
partner_misp_lk = "DOWwzI8SCLaZQ4LPKSHhOzbLTnYasK6EMmTO0QQzzabCbAjGn4"
partner_id = "core123"

[mosip_auth_server]
ida_auth_domain_uri = 'https://api-internal.env.mosip.net'
ida_auth_url = 'https://api-internal.env.mosip.net/idauthentication/v1'


[crypto_encrypt]
symmetric_key_size = 256
symmetric_nonce_size = 128
symmetric_gcm_tag_size = 128
# certificate from the below path is used to encrypt the Auth Request.
encrypt_cert_path = "./ida_fir_cert.pem"
# used to decrypt the received response
decrypt_p12_file_path = "./keystore.p12"
decrypt_p12_file_password = "Password@123"

[crypto_signature]
algorithm = 'RS256'
sign_p12_file_path =  './keystore.p12'
sign_p12_file_password = 'Password@123'

[logging]
log_file_path = 'authenticator.log'
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
loglevel = "DEBUG" # can be one of "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL"